config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "languages#index"
  resource :profile, only:[:show, :edit, :update]
  resource :service, only:[:edit, :update]
  resources :languages do
    resources :articles 
  end
  resources :articles do
    resources :comments
  end
  resources :accounts, only:[:show] do
    resources :follows, only:[:index,:create]
    resources :unfollows, only:[:index,:create]
    resource :relation, only:[:show]
  end
  resources :errors, only:[:show]
  resource :timeline, only:[:index, :show]
  resources :searches, only: [:index]
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many_attached :article_imgs
    belongs_to :language

    validates :title, presence: true
    validates :error, presence: true
    validates :number, presence: true

    def self.search(search)
        if search
          Article.where(['title LIKE ?', "%#{search}%"])
        else
          Article.all
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
    def index
        @language = Language.find(params[:language_id])
        @articles = @language.articles
    end
    def show
        @language = Language.find(params[:language_id])
        @article = Article.find(params[:id])
    end
    def new
        language = Language.find(params[:language_id])
        @article = language.articles.build
    end
    def create
        language = Language.find(params[:language_id])
        @article = language.articles.build(article_params)
        if @article.save
            redirect_to language_articles_path, notice: 'save'
        else
            flash.now[:error] = 'miss'
            render :new
        end
    end
    def edit
        language = current_user.languages.find(params[:language_id])
        @article = language.articles.find(params[:id])
    end
    def update
        language = current_user.languages.find(params[:language_id])
        @article = language.articles.find(params[:id])
        if @article.update(article_params)
            redirect_to language_article_path(language)
        else
            flash.now[:error] = 'miss'
            render :edit
        end
    end
    def destroy
        language = current_user.languages.find(params[:language_id])
        article = language.articles.find(params[:id])
        article.destroy!
        redirect_to language_articles_path(language), notice: 'delete'
    end
    private
    def article_params
        params.require(:article).permit(:title, :error, :content, :memo, :number, article_imgs:[])
    end
end

app/views/articles/edit.html.haml
.container
  = form_with(model: @article, url: language_article_path(@article.language), method: 'put', local: true) do |f|
    .field
      %div
        = f.label :title, 'title', class: 'label'
      %div
        = f.text_field :title, class: 'form'
    .field
      %div
        = f.label :error, 'error message', class: 'label'
      %div
        = f.text_area :error, class: 'form'
    .field
      %div
        = f.label :content, 'answer', class: 'label'
      %div
        = f.text_area :content, class: 'form'
    .field
      %div
        = f.label :article_imgs, 'image', class: 'label'
      %div
        = f.file_field :article_imgs, multiple: true, class: 'form'
    .field
      %div
        = f.label :memo, 'memo', class: 'label'
      %div
        = f.text_area :memo, class: 'form'
    .field
      %div
        = f.label :number, 'number', class: 'label'
      %div
        = f.number_field :number, class: 'form'
    = f.submit 'POST', class: 'btn'

app/views/articles/index.html.haml
.container
  .article_top
    .user_name
      = @language.user.account_name
    .article_post
      - if @language.user === current_user
        = link_to '+POST', new_language_article_path(@language)
  .articles
    - @articles.each do |article|
      = render 'commons/article', article: article

app/views/articles/new.html.haml
.container
  = form_with(model: @article, url: language_articles_path(@article.language), method: 'post', local: true) do |f|
    .field
      %div
        = f.label :title, 'title', class: 'label'
      %div
        = f.text_field :title, class: 'form'
    .field
      %div
        = f.label :error, 'error message', class: 'label'
      %div
        = f.text_area :error, class: 'form'
    .field
      %div
        = f.label :content, 'answer', class: 'label'
      %div
        = f.text_area :content, class: 'form'
    .field
      %div
        = f.label :article_imgs, 'image', class: 'label'
      %div
        = f.file_field :article_imgs, multiple: true, class: 'form'
    .field
      %div
        = f.label :memo, 'memo', class: 'label'
      %div
        = f.text_area :memo, class: 'form'
    .field
      %div
        = f.label :number, 'number', class: 'label'
      %div
        = f.number_field :number, class: 'form'
    = f.submit 'POST', class: 'btn'

app/views/articles/show.html.haml
.container#article-show{data: {article_id: @article.id}}
  .article_detail
    .article_name
      = link_to "#{@language.user.account_name}" , account_path(@language.user.id)
    .article_item
      - if @language.user === current_user
        = link_to 'edit', edit_language_article_path(@language)
        = link_to 'delete', language_article_path(@language), data: {method: 'delete', confirm: 'ok?'}
    .article_title
      %p Title
      = @article.title
    .article_error
      %p Error
      = @article.error
    .article_img
      - if @article.article_imgs.present?
        %p Image
        - @article.article_imgs.each do |article_img|
          = image_tag article_img
    -if @article.content.present?
      .answer
        Answer
      .answer_nav.hidden
        .article_content
          %p Answer
          = @article.content
        .article_memo
          %p Memo
          = @article.memo
  .comment
    Comment
  .comments_container.hidden
    .comment_form
      = text_area_tag :comment_content, '', class: 'comment_text'
    .comment_post
      AddComment
    .comment_nav
      %p.comment_view コメント一覧
= javascript_pack_tag 'article'
= javascript_pack_tag 'comment'