config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "languages#index"
  resource :profile, only:[:show, :edit, :update]
  resource :service, only:[:edit, :update]
  resources :languages do
    resources :articles 
  end
  resources :articles do
    resources :comments
  end
  resources :accounts, only:[:show] do
    resources :follows, only:[:index,:create]
    resources :unfollows, only:[:index,:create]
    resource :relation, only:[:show]
  end
  resources :errors, only:[:show]
  resource :timeline, only:[:index, :show]
  resources :searches, only: [:index]
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :articles, dependent: :destroy
    belongs_to :user

    validates :language, presence: true
    validates :title, presence: true
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
    before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
    def index
        if user_signed_in?
          @languages = current_user.languages
        else
            redirect_to timeline_path
        end
    end
    def new
        @language = current_user.languages.build
    end
    def create
        @language = current_user.languages.build(language_params)
        if @language.save
            redirect_to languages_path,  notice: 'save'
        else
            flash.now[:error] = 'miss'
            render :new
        end
    end
    def edit
        @language = current_user.languages.find(params[:id])
    end
    def update
        @language = current_user.languages.find(params[:id])
        if @language.update(language_params)
            redirect_to root_path
        else
            flash.now[:error] = 'miss'
            render :edit
        end
    end
    def destroy
        language = current_user.languages.find(params[:id])
        language.destroy!
        redirect_to root_path, notice: 'delete'
    end
    private
    def language_params
        params.require(:language).permit(:language, :title)
    end
end

app/views/languages/edit.html.haml
.container
  = form_with(model: @language, url: language_path(@language), method: 'put', local: true) do |f|
    .field
      %div
        = f.label :language, 'language', class: 'label'
      %div
        = f.text_field :language, class: 'form'
    .field
      %div
        = f.label :title, 'title', class: 'label'
      %div
        = f.text_area :title, class: 'form'
    = f.submit 'Update', class: 'btn'

app/views/languages/index.html.haml
.container
  .language_top
    %div= link_to 'profile', profile_path
    %div= @current_user.account_name
    %div= link_to '+POST', new_language_path
  = render 'commons/language', languages: @languages
        

app/views/languages/new.html.haml
.container
  = form_with(model: @language, url: languages_path, method: 'post', local: true) do |f|
    .field
      %div
        = f.label :language, 'language', class: 'label'
      %div
        = f.text_field :language, class: 'form'
    .field
      %div
        = f.label :title, 'title', class: 'label'
      %div
        = f.text_area :title, class: 'form'
    = f.submit 'POST', class: 'btn'