config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "languages#index"
  resource :profile, only:[:show, :edit, :update]
  resource :service, only:[:edit, :update]
  resources :languages do
    resources :articles 
  end
  resources :articles do
    resources :comments
  end
  resources :accounts, only:[:show] do
    resources :follows, only:[:index,:create]
    resources :unfollows, only:[:index,:create]
    resource :relation, only:[:show]
  end
  resources :errors, only:[:show]
  resource :timeline, only:[:index, :show]
  resources :searches, only: [:index]
end

app/views/commons/_article.html.haml
= link_to language_article_path(id: article.id, language_id: article.language_id) do
  .article
    .article_item
      .article_title
        = article.title
      .article_number
        = article.number
    .article_error
      = article.error

app/views/commons/_language.html.haml
- languages.each do |language|
  = link_to language_articles_path(language) do
    .language_nav
      .language_item
        = language.language
      .language_item
        = language.title
        - if current_user === language.user
          %div
            = link_to 'delete', language_path(language), data: {method: 'delete', confirm: 'ok?'}
            = link_to 'edit', edit_language_path(language)

app/views/commons/_profile.html.haml
.profile
  .profile_name
    - if user.profile&.avatar&.attached?
      = image_tag user.profile.avatar
    = user.account_name
  .profile_top
    - if user === current_user
      .profile_left
        - if user.profile&.url.present?
          = link_to 'servise', "#{user.profile.url}"
        - else 
          %div= link_to '+ servise', edit_service_path
      .profile_right
        %div= link_to 'edit', edit_profile_path
        %div= link_to 'Logout', destroy_user_session_path, data: {method: 'delete', confirm: 'ok?'}
    - else
      - if user.profile&.url.present?
        = link_to 'servise', "#{user.profile.url}"
      - else 
        %div= 'servise'
      .follows
        .follow.hidden
          Follow
        .unfollow.hidden
          unFollow
  .follow_nav
    = link_to account_follows_path(user.id) do
      = user.followings.count
      %br Follow
    = link_to account_unfollows_path(user.id) do
      = user.followers.count
      %br Follower
  - if user.profile.present?
    .profile_item
      .job
        %p job
        = user.profile.job
      .introduction
        %p introduction 
      = user.profile.introduction
  = link_to error_path(user.id) do
    .error_all
      All Errors