config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "languages#index"
  resource :profile, only:[:show, :edit, :update]
  resource :service, only:[:edit, :update]
  resources :languages do
    resources :articles 
  end
  resources :articles do
    resources :comments
  end
  resources :accounts, only:[:show] do
    resources :follows, only:[:index,:create]
    resources :unfollows, only:[:index,:create]
    resource :relation, only:[:show]
  end
  resources :errors, only:[:show]
  resource :timeline, only:[:index, :show]
  resources :searches, only: [:index]
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
    def show
        if user_signed_in?
            user_ids = current_user.followings.pluck(:id)
            @languages = Language.where(user_id: user_ids).order(id: :desc)
        end
        @articles = Article.all.order(id: :desc)
    end
end

app/views/timelines/_timeline.html.haml
.article_name
  = link_to account_path(article.language.user.id) do
    = article.language.user.account_name
= render 'commons/article', article: article

app/views/timelines/show.html.haml
.container
  .search
    = form_tag(searches_path,:method => 'get') do
      = text_field_tag :search
      = submit_tag 'Search', :name => nil
  - if user_signed_in?
    .article_followings
      - @languages.each do |language|
        - language.articles.each do |article|
          = render partial: 'timeline', locals:{article: article}
    .article_all.hidden
      - @articles.each do |article|
        = render partial: 'timeline', locals:{article: article}
  - else
    .article_all
      - @articles.each do |article|
        = render partial: 'timeline', locals:{article: article}
= javascript_pack_tag 'timeline'